# Generated by Django 4.2 on 2023-04-27 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EasyLearn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='cat',
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category', to='EasyLearn.category'),
        ),
    ]
